//! A shared, type-erased view of one static object pool.

use core::marker::PhantomData;

use crate::StaticHandle;

/// An object pool generated by `static_objects!`.
///
/// The concrete handle type identifies one pool. Its object slice is selected
/// at compile time when constructing a [`HandleShared`].
///
/// # Safety
/// `LENGTH` must equal `OBJECTS.len()` in the raw integer type. The length
/// must fit that type; otherwise `HandleShared::resolve` could read past the pool.
pub unsafe trait StaticObjectPool<Object: 'static, Raw: PoolHandle>: StaticHandle<Target = Object, Raw = Raw> {
    const OBJECTS: &'static [Object];
    const LENGTH: Raw;
}

/// Converts a nonzero pool-local raw handle to a zero-based index.
pub trait PoolHandle: Copy {
    const MAX: usize;
    fn value(self) -> usize;
    fn index(self) -> usize;
}

impl PoolHandle for u8 {
    const MAX: usize = u8::MAX as usize;

    fn value(self) -> usize {
        usize::from(self)
    }

    fn index(self) -> usize {
        usize::from(
            self.checked_sub(1)
                .expect("static_objects!: invalid shared handle"),
        )
    }
}

impl PoolHandle for u16 {
    const MAX: usize = u16::MAX as usize;

    fn value(self) -> usize {
        usize::from(self)
    }

    fn index(self) -> usize {
        usize::from(
            self.checked_sub(1)
                .expect("static_objects!: invalid shared handle"),
        )
    }
}

/// A static pool whose concrete handle type is erased after construction.
///
/// The resulting type depends only on `Object` and `Raw`, so distinct pools
/// with those same types share runtime resolution code. Packed fields are
/// copied by value before use; no references to unaligned fields are formed.
#[repr(C, packed)]
pub struct HandleShared<Object: 'static, Raw> {
    first_object: Option<&'static Object>,
    len: Raw,
    _raw: PhantomData<fn() -> Raw>,
}

impl<Object: 'static, Raw: Copy> Copy for HandleShared<Object, Raw> {}

impl<Object: 'static, Raw: Copy> Clone for HandleShared<Object, Raw> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<Object: 'static, Raw: PoolHandle> HandleShared<Object, Raw> {
    pub const fn new<Pool: StaticObjectPool<Object, Raw>>() -> Self {
        let objects = Pool::OBJECTS;
        assert!(objects.len() <= Raw::MAX, "static_objects!: shared pool exceeds raw handle width");
        Self {
            first_object: objects.first(),
            len: Pool::LENGTH,
            _raw: PhantomData,
        }
    }

    pub fn len(&self) -> usize {
        self.len.value()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    pub fn resolve(&self, handle: Raw) -> &'static Object {
        let index = handle.index();
        assert!(index < self.len(), "static_objects!: shared handle outside pool");
        let first = self
            .first_object
            .expect("static_objects!: empty shared pool");
        // SAFETY: new took first from the original static slice and stored its
        // exact length; index was checked against that length.
        unsafe { &*(first as *const Object).add(index) }
    }
}
